CREATE TABLE company (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    admin_id INT(11) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    unique_info TEXT NOT NULL,
    password VARCHAR(255) NOT NULL,
    logo VARCHAR(255) DEFAULT NULL, -- Added logo column
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE
);
