CREATE TABLE super_admins (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  contact VARCHAR(15) NOT NULL,
  image VARCHAR(255) DEFAULT NULL, -- Profile image (optional)
  role INT(11) NOT NULL DEFAULT 1, -- Fixed as "Super Admin" (role_id = 1)
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (role) REFERENCES roles(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
